// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-i75U0XpVHCZuWVED4N6lcY2GduqoCjU',
    appId: '1:115246507033:web:aa40e610394508204d7688',
    messagingSenderId: '115246507033',
    projectId: 'autokaji',
    authDomain: 'autokaji.firebaseapp.com',
    storageBucket: 'autokaji.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVZFBpfg5A7I3nKzPXSRNMy7LErdOyuE',
    appId: '1:115246507033:android:d9ef8761f8a245934d7688',
    messagingSenderId: '115246507033',
    projectId: 'autokaji',
    storageBucket: 'autokaji.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx6y69jwSKnZUpuyMyKobdhAJ5Dml8zCw',
    appId: '1:115246507033:ios:5d87423974ea040e4d7688',
    messagingSenderId: '115246507033',
    projectId: 'autokaji',
    storageBucket: 'autokaji.firebasestorage.app',
    iosBundleId: 'com.gyuhan.autokaji',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx6y69jwSKnZUpuyMyKobdhAJ5Dml8zCw',
    appId: '1:115246507033:ios:0eadf23d7e2f68974d7688',
    messagingSenderId: '115246507033',
    projectId: 'autokaji',
    storageBucket: 'autokaji.firebasestorage.app',
    iosBundleId: 'com.example.autokaji',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-i75U0XpVHCZuWVED4N6lcY2GduqoCjU',
    appId: '1:115246507033:web:4dc96c72d08ce6104d7688',
    messagingSenderId: '115246507033',
    projectId: 'autokaji',
    authDomain: 'autokaji.firebaseapp.com',
    storageBucket: 'autokaji.firebasestorage.app',
  );
}
